CREATE SEQUENCE REST_ID_SEQ START WITH 1
  MAXVALUE 1000000000
  NO CYCLE;

CREATE TABLE RESTAURANT(
	REST_ID BIGINT DEFAULT NEXTVAL('REST_ID_SEQ') CONSTRAINT RESTAURANT_PK PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	LOCATION VARCHAR(100) NOT NULL,
	PRICE_RANGE SMALLINT CHECK (PRICE_RANGE>=1 AND PRICE_RANGE<=5)
);

CREATE SEQUENCE REVIEW_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NO CYCLE;

CREATE TABLE REVIEWS(
	REVIEW_ID BIGINT DEFAULT NEXTVAL('REVIEW_ID_SEQ')  CONSTRAINT REVIEWS_PK PRIMARY KEY,
	REST_ID BIGINT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	RATING SMALLINT CHECK (RATING>=0 AND RATING<=5),
	CONSTRAINT REVIEWS_FK FOREIGN KEY (REST_ID) REFERENCES RESTAURANT(REST_ID)
);